create table
  public.cart_items (
    line_item_id integer generated always as identity,
    cart_id integer not null default 0,
    customer_id integer null,
    potion integer not null,
    quantity integer not null default 0,
    constraint cart_items_pkey primary key (line_item_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint cart_items_customer_id_fkey foreign key (customer_id) references customers (customer_id),
    constraint cart_items_potion_fkey foreign key (potion) references potions (sku)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id integer generated always as identity,
    timestamp timestamp with time zone null default now(),
    customer_id integer null,
    checkout boolean not null default false,
    constraint carts_pkey primary key (cart_id),
    constraint carts_customer_id_fkey foreign key (customer_id) references customers (customer_id)
  ) tablespace pg_default;

create table
  public.customers (
    customer_id integer generated always as identity,
    timestamp timestamp with time zone null default now(),
    name text not null,
    level integer not null,
    class text not null,
    constraint customers_pkey primary key (customer_id)
  ) tablespace pg_default;

create table
  public.gold_ledger (
    ledger_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    gold integer null,
    constraint gold_ledger_pkey primary key (ledger_id)
  ) tablespace pg_default;

create table
  public.ml_ledger (
    ledger_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    red_ml integer null,
    green_ml integer null,
    blue_ml integer null,
    dark_ml integer null,
    constraint ml_ledger_pkey primary key (ledger_id)
  ) tablespace pg_default;

create table
  public.potion_ledger (
    ledger_id integer generated always as identity,
    created_at timestamp with time zone null default now(),
    potion_sku integer null,
    change integer not null,
    constraint potion_ledger_entries_pkey primary key (ledger_id),
    constraint potion_ledger_entries_potion_sku_fkey foreign key (potion_sku) references potions (sku)
  ) tablespace pg_default;

create table
  public.potions (
    sku integer generated always as identity,
    created_at timestamp with time zone null default now(),
    name text not null,
    red_ml integer not null,
    green_ml integer not null,
    blue_ml integer not null,
    dark_ml integer not null,
    price integer not null,
    constraint potions_pkey primary key (sku)
  ) tablespace pg_default;

create table
  public.visits (
    visit_id integer not null,
    created_at timestamp with time zone null default now(),
    name text not null,
    class text not null,
    level integer not null,
    id integer generated by default as identity,
    constraint visits_pkey primary key (id)
  ) tablespace pg_default;
